import Head from 'next/head';
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
import '../styles/globals.css';
import Script from 'next/script';

export default function App({ Component, pageProps }) {
	return (
		<>
			<Head>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<Script
					lazyOnload={true}
					src='https://unpkg.com/@themesberg/flowbite@latest/dist/flowbite.bundle.js'></Script>
			</Head>{' '}
			<Navbar /> <Component {...pageProps} /> <Footer />
		</>
	);
}
