import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Sector1 from '../components/Section1'
import Sector2 from '../components/Section2'
import Sector3 from '../components/Section3'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>GDSC Official</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Navbar />
        <div className='sections flex flex-col items-center px-3 sm:px-8 md:px-16 '>
          <Sector1 />
          <Sector2 />
          <Sector3 />
         
        </div>
      </main>
    </>
  )
}
