import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Section1 from '../components/Home/Section1'
import Section2 from '../components/Home/Section2'
import Section3 from '../components/Home/Section3'
import FAQ from '../components/Home/FAQ'
import Footer from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>GDSC Official</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main >
        <Navbar />
        <div className='sections flex flex-col items-center px-3 sm:px-8 md:px-16 '>
          <Section1 />
          <Section2 />
          <FAQ />
          <Section3 />
        </div>
        <Footer />
      </main>
    </>
  )
}
